### ISSUE TITLE
Code needs documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [aachar5/QBOcomposite#1]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote!

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by aachar5** [comment]
I have added the documentation for the codes. Please inform me in case of any mistakes or errors in the analysis.

**Comment by luisortizuriarte** [comment]
The documentation does make it easier to follow. Thanks! Closing this issue.
