### ISSUE TITLE
Tidying up after data exploration

### ISSUE THREAD

**Issue by luisortizuriarte** [aachar5/QBOcomposite#2]
In your submitted notebook, you dedicate a lot of cells to exploratory analysis with various outputs printed out. As you work and start resolving your issues, either remove erroneous code or consolidate it into single cells with fewer printouts. This will help you avoid duplication and errors and make it easier to document as well.

**Comment by aachar5** [comment]
Okay, I will keep this in mind from now on.

**Comment by luisortizuriarte** [comment]
With the documentation and the redone work, things are much easier to follow. Closing this issue.
