### ISSUE TITLE
Issue adding cyclic point

### ISSUE THREAD

**Issue by luisortizuriarte** [aachar5/QBOcomposite#3]
It seems there is an issue with how you entered the longitude data to the add_cyclic_point function. You can start looking into this by seeing if` comp_temp[i]['longitude']` returns an actual array of longitudes or if it returns something else.

**Comment by aachar5** [comment]
I have addressed and corrected it in the new file I added, [https://github.com/aachar5/3rdassignment/blob/main/finalassignment.ipynb](url)

**Comment by luisortizuriarte** [comment]
Great! The issue is solved, so closing it.
