### ISSUE TITLE
Plotting loop and errors

### ISSUE THREAD

**Issue by pdirmeyer** [aachar5/QBOcomposite#6]
The `lat` dimension is passed to `contourf`, but not longitude. You need to pass either both (to be able to use georegistered information in `cartopy` or label the latitudes and longitudes) or none.

Also, the `for` loop and handling of the composites is a bit confused - `qbo` is `comp_temp[i]` is `data` as you have defined them - you don't need all three.

**Comment by aachar5** [comment]
The correction for contourf has been done passing both the lat and lon coordinates.
